// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalCodesDao is internal type for wrapping internal DAO implements.
type internalCodesDao = *internal.CodesDao

// codesDao is the data access object for table codes.
// You can define custom methods on it to extend its functionality as you wish.
type codesDao struct {
	internalCodesDao
}

var (
	// Codes is globally public accessible object for table codes operations.
	Codes = codesDao{
		internal.NewCodesDao(),
	}
)

// Fill with you ideas below.
