// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalDocumentsDao is internal type for wrapping internal DAO implements.
type internalDocumentsDao = *internal.DocumentsDao

// documentsDao is the data access object for table documents.
// You can define custom methods on it to extend its functionality as you wish.
type documentsDao struct {
	internalDocumentsDao
}

var (
	// Documents is globally public accessible object for table documents operations.
	Documents = documentsDao{
		internal.NewDocumentsDao(),
	}
)

// Fill with you ideas below.
