// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalDocumentTemplateDao is internal type for wrapping internal DAO implements.
type internalDocumentTemplateDao = *internal.DocumentTemplateDao

// documentTemplateDao is the data access object for table document-template.
// You can define custom methods on it to extend its functionality as you wish.
type documentTemplateDao struct {
	internalDocumentTemplateDao
}

var (
	// DocumentTemplate is globally public accessible object for table document-template operations.
	DocumentTemplate = documentTemplateDao{
		internal.NewDocumentTemplateDao(),
	}
)

// Fill with you ideas below.
