// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalGroupMembersDao is internal type for wrapping internal DAO implements.
type internalGroupMembersDao = *internal.GroupMembersDao

// groupMembersDao is the data access object for table group_members.
// You can define custom methods on it to extend its functionality as you wish.
type groupMembersDao struct {
	internalGroupMembersDao
}

var (
	// GroupMembers is globally public accessible object for table group_members operations.
	GroupMembers = groupMembersDao{
		internal.NewGroupMembersDao(),
	}
)

// Fill with you ideas below.
