// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalGroupConnectDao is internal type for wrapping internal DAO implements.
type internalGroupConnectDao = *internal.GroupConnectDao

// groupConnectDao is the data access object for table group-connect.
// You can define custom methods on it to extend its functionality as you wish.
type groupConnectDao struct {
	internalGroupConnectDao
}

var (
	// GroupConnect is globally public accessible object for table group-connect operations.
	GroupConnect = groupConnectDao{
		internal.NewGroupConnectDao(),
	}
)

// Fill with you ideas below.
