// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalGroupsDao is internal type for wrapping internal DAO implements.
type internalGroupsDao = *internal.GroupsDao

// groupsDao is the data access object for table groups.
// You can define custom methods on it to extend its functionality as you wish.
type groupsDao struct {
	internalGroupsDao
}

var (
	// Groups is globally public accessible object for table groups operations.
	Groups = groupsDao{
		internal.NewGroupsDao(),
	}
)

// Fill with you ideas below.
