// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalGroupTemplateDao is internal type for wrapping internal DAO implements.
type internalGroupTemplateDao = *internal.GroupTemplateDao

// groupTemplateDao is the data access object for table group-template.
// You can define custom methods on it to extend its functionality as you wish.
type groupTemplateDao struct {
	internalGroupTemplateDao
}

var (
	// GroupTemplate is globally public accessible object for table group-template operations.
	GroupTemplate = groupTemplateDao{
		internal.NewGroupTemplateDao(),
	}
)

// Fill with you ideas below.
