// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_chat_server/internal/dao/internal"
)

// internalTokensDao is internal type for wrapping internal DAO implements.
type internalTokensDao = *internal.TokensDao

// tokensDao is the data access object for table tokens.
// You can define custom methods on it to extend its functionality as you wish.
type tokensDao struct {
	internalTokensDao
}

var (
	// Tokens is globally public accessible object for table tokens operations.
	Tokens = tokensDao{
		internal.NewTokensDao(),
	}
)

// Fill with you ideas below.
